export const FORM_PROJECT = 'FORM_PROJECT'
export const GETPROJECTS = 'GETPROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const CURRENT_PROJECT = 'CURRENT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const TASKS_PROJECT = 'TASKS_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const VALIDATE_TASK = 'VALIDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const STATE_TASK = 'STATE_TASK'

export const CURRENT_TASK = 'CURRENT_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const ClEANTASK = 'ClEANTASK'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const GETTING_USER = 'GETTING_USER'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const PROJECT_ERROR = 'PROJECT_ERROR'
